### PR TITLE
Components cleanup

### PR DESCRIPTION
**Pull request by Nickman87**
Hi,

I'm trying to use your component but I was in need of some more flexibility concerning the size of the scrollbar (not just a fixed with, but a relative width) and styling (I added some classnames)
As this was not possible I started to modify the existing component to achieve what I needed and while doing that I also created some more sub-components to clean up the code and tried to remove as much state as possible to make it less error prone and easier to read.

What do you think about it?

(The test you made to check if it is an actual component fails but I don't quite understand what you are trying to test there...)

### CODE REVIEW

**Comment by jckdrpr** [comment]
Wow awesome I can't thank you enough as I wanted to do most of the things myself. will do a new release in a day or two I hope that's fine with you and again thank you.

**Comment by Nickman87** [comment]
I tried the touch controls but they didn't seem to work on the original version, but I'll check it out tomorrow :)

**Comment by jckdrpr** [comment]
I had a pull request a few days back and after that they were working. you can check out the code diff there.

**Comment by jckdrpr** [comment]
I have fixed the touch controls and also removed that stupid test case (it was just to check if ava is running fine or not anyway I am still struggling with how and what to test UI) and again thanks for your contribution.

**Comment by Nickman87** [comment]
Awesome, I was just thinking in the car that the touch would be failing because it is in the wrong component :D.
For the tests, I also find it pretty hard to determine what to test and what not for UI components, you would make some basic tests cases where you provide some props to a component and check if the expected result is rendered, but those kinds of tests are very prone to fail when you change even a small part of your UI layout...

**Pull request merged**
